#!/bin/bash
#SBATCH --job-name=test
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=48000m
#SBATCH --time=60:00
#SBATCH --account=zhengya98
#SBATCH --partition=spgpu
#SBATCH --gpus-per-node=1

module purge
module load python/3.10.4
module unload pytorch 2>/dev/null || true
module load cuda/12.8.1

if [ -f ".venv/bin/activate" ]; then
  # Activate local virtual environment created by install.sh
  # shellcheck disable=SC1091
  source .venv/bin/activate
else
  echo "[ERROR] .venv/bin/activate not found. Did you run install.sh?"
  exit 1
fi

unset PYTHONPATH
unset PYTHONHOME
export PYTHONNOUSERSITE=1

set -euo pipefail

echo "[INFO] Job started at: $(date)"
echo "[INFO] Host: $(hostname)"

TEST_MODE="${TEST_MODE:-simple}"
ATTN_TYPE="${ATTN_TYPE:-RetrievalAttention}"
MODEL_NAME="${MODEL_NAME:-meta-llama/Llama-3.1-8B-Instruct}"
DTYPE="${DTYPE:-bf16}"
BATCH_SIZE="${BATCH_SIZE:-1}"
GEN_LEN="${GEN_LEN:-100}"
LOW_CPU_MEM_USAGE="${LOW_CPU_MEM_USAGE:-1}"
TOKEN_BUDGET_OVERRIDE="${TOKEN_BUDGET_OVERRIDE:-100}"
RETRIEVALATTN_GPU_TOPK="${RETRIEVALATTN_GPU_TOPK:-0}"
RETRIEVALATTN_CUSTOM_QK_TOPK="${RETRIEVALATTN_CUSTOM_QK_TOPK:-0}"
RETRIEVALATTN_CUSTOM_QK_TOPK_BLOCK_Q="${RETRIEVALATTN_CUSTOM_QK_TOPK_BLOCK_Q:-64}"
RETRIEVALATTN_CUSTOM_QK_TOPK_LAUNCH_Q_CHUNK="${RETRIEVALATTN_CUSTOM_QK_TOPK_LAUNCH_Q_CHUNK:-1024}"
RETRIEVALATTN_CUSTOM_QK_TOPK_BLOCK_D="${RETRIEVALATTN_CUSTOM_QK_TOPK_BLOCK_D:-32}"
RETRIEVALATTN_CUSTOM_QK_TOPK_BLOCK_K="${RETRIEVALATTN_CUSTOM_QK_TOPK_BLOCK_K:-256}"
RETRIEVALATTN_FA_FUSED_PREFILL="${RETRIEVALATTN_FA_FUSED_PREFILL:-1}"
RETRIEVALATTN_FA_SHADOW_COMPARE="${RETRIEVALATTN_FA_SHADOW_COMPARE:-0}"
RETRIEVALATTN_FA_SHADOW_SAMPLE="${RETRIEVALATTN_FA_SHADOW_SAMPLE:-256}"
RETRIEVALATTN_FUSED_PREFILL_OVERLAP="${RETRIEVALATTN_FUSED_PREFILL_OVERLAP:-1}"
RETRIEVALATTN_FUSED_PREFILL_OVERLAP_WORKERS="${RETRIEVALATTN_FUSED_PREFILL_OVERLAP_WORKERS:-1}"
RETRIEVALATTN_Q_BLOCK="${RETRIEVALATTN_Q_BLOCK:-512}"
RETRIEVALATTN_K_BLOCK="${RETRIEVALATTN_K_BLOCK:-4096}"
RETRIEVALATTN_OVERLAP="${RETRIEVALATTN_OVERLAP:-1}"
RETRIEVALATTN_LAYER_GPU_CACHE="${RETRIEVALATTN_LAYER_GPU_CACHE:-1}"
RETRIEVALATTN_DECODE_INDEX="${RETRIEVALATTN_DECODE_INDEX:-faiss}"
RETRIEVALATTN_SEED_MODE="${RETRIEVALATTN_SEED_MODE:-graph_only}"
RETRIEVALATTN_QUERY_MODE="${RETRIEVALATTN_QUERY_MODE:-per_head}"
RETRIEVALATTN_SCORE_MODE="${RETRIEVALATTN_SCORE_MODE:-ip}"
RETRIEVALATTN_GRAPH_BUILDER="${RETRIEVALATTN_GRAPH_BUILDER:-roar}"
RETRIEVALATTN_ROAR_NQ="${RETRIEVALATTN_ROAR_NQ:-32}"
RETRIEVALATTN_ROAR_L="${RETRIEVALATTN_ROAR_L:-128}"
RETRIEVALATTN_ROAR_M="${RETRIEVALATTN_ROAR_M:-32}"
RETRIEVALATTN_ROAR_ENABLE_ENHANCE="${RETRIEVALATTN_ROAR_ENABLE_ENHANCE:-1}"
RETRIEVALATTN_ROAR_ENHANCE_L="${RETRIEVALATTN_ROAR_ENHANCE_L:-256}"
RETRIEVALATTN_ROAR_ENTRY="${RETRIEVALATTN_ROAR_ENTRY:-hub}"
RETRIEVALATTN_ROAR_MAX_QUERY_PER_PIVOT="${RETRIEVALATTN_ROAR_MAX_QUERY_PER_PIVOT:-0}"
RETRIEVALATTN_ROAR_LOG="${RETRIEVALATTN_ROAR_LOG:-1}"
RETRIEVALATTN_GRAPH_EXPAND="${RETRIEVALATTN_GRAPH_EXPAND:-1}"
RETRIEVALATTN_EXPAND_WIDTH="${RETRIEVALATTN_EXPAND_WIDTH:-48}"
RETRIEVALATTN_MIN_VISITS="${RETRIEVALATTN_MIN_VISITS:-96}"
RETRIEVALATTN_MAX_VISITS="${RETRIEVALATTN_MAX_VISITS:-2048}"
RETRIEVALATTN_STOP_PATIENCE="${RETRIEVALATTN_STOP_PATIENCE:-1}"
RETRIEVALATTN_STOP_MARGIN="${RETRIEVALATTN_STOP_MARGIN:-0.001}"
RETRIEVALATTN_FRONTIER_TOPN="${RETRIEVALATTN_FRONTIER_TOPN:-0}"
RETRIEVALATTN_RERANK="${RETRIEVALATTN_RERANK:-1}"
RETRIEVALATTN_RERANK_AGG="${RETRIEVALATTN_RERANK_AGG:-max}"
RETRIEVALATTN_SEED_RATIO="${RETRIEVALATTN_SEED_RATIO:-0.7}"
RETRIEVALATTN_CAND_MULT="${RETRIEVALATTN_CAND_MULT:-4}"
RETRIEVALATTN_SEED_K_MULT="${RETRIEVALATTN_SEED_K_MULT:-1}"
RETRIEVALATTN_SEED_PREV_K="${RETRIEVALATTN_SEED_PREV_K:-256}"
RETRIEVALATTN_SEED_HUB_K="${RETRIEVALATTN_SEED_HUB_K:-64}"
RETRIEVALATTN_SEED_TAIL_K="${RETRIEVALATTN_SEED_TAIL_K:-32}"
RETRIEVALATTN_DEBUG="${RETRIEVALATTN_DEBUG:-0}"
RETRIEVALATTN_ASSERT_NONEMPTY="${RETRIEVALATTN_ASSERT_NONEMPTY:-0}"
RETRIEVALATTN_VALIDATE_PARITY="${RETRIEVALATTN_VALIDATE_PARITY:-0}"
RETRIEVALATTN_DECODE_PROFILE="${RETRIEVALATTN_DECODE_PROFILE:-1}"

echo "[INFO] TEST_MODE=${TEST_MODE}"
echo "[INFO] ATTN_TYPE=${ATTN_TYPE}"
echo "[INFO] MODEL_NAME=${MODEL_NAME}"
echo "[INFO] DTYPE=${DTYPE}"
echo "[INFO] BATCH_SIZE=${BATCH_SIZE}"
echo "[INFO] GEN_LEN=${GEN_LEN}"
echo "[INFO] LOW_CPU_MEM_USAGE=${LOW_CPU_MEM_USAGE}"
echo "[INFO] TOKEN_BUDGET_OVERRIDE=${TOKEN_BUDGET_OVERRIDE}"
echo "[INFO] RETRIEVALATTN_GPU_TOPK=${RETRIEVALATTN_GPU_TOPK}"
echo "[INFO] RETRIEVALATTN_CUSTOM_QK_TOPK=${RETRIEVALATTN_CUSTOM_QK_TOPK}"
echo "[INFO] RETRIEVALATTN_CUSTOM_QK_TOPK_BLOCK_Q=${RETRIEVALATTN_CUSTOM_QK_TOPK_BLOCK_Q}"
echo "[INFO] RETRIEVALATTN_CUSTOM_QK_TOPK_LAUNCH_Q_CHUNK=${RETRIEVALATTN_CUSTOM_QK_TOPK_LAUNCH_Q_CHUNK}"
echo "[INFO] RETRIEVALATTN_CUSTOM_QK_TOPK_BLOCK_D=${RETRIEVALATTN_CUSTOM_QK_TOPK_BLOCK_D}"
echo "[INFO] RETRIEVALATTN_CUSTOM_QK_TOPK_BLOCK_K=${RETRIEVALATTN_CUSTOM_QK_TOPK_BLOCK_K}"
echo "[INFO] RETRIEVALATTN_FA_FUSED_PREFILL=${RETRIEVALATTN_FA_FUSED_PREFILL}"
echo "[INFO] RETRIEVALATTN_FA_SHADOW_COMPARE=${RETRIEVALATTN_FA_SHADOW_COMPARE}"
echo "[INFO] RETRIEVALATTN_FA_SHADOW_SAMPLE=${RETRIEVALATTN_FA_SHADOW_SAMPLE}"
echo "[INFO] RETRIEVALATTN_FUSED_PREFILL_OVERLAP=${RETRIEVALATTN_FUSED_PREFILL_OVERLAP}"
echo "[INFO] RETRIEVALATTN_FUSED_PREFILL_OVERLAP_WORKERS=${RETRIEVALATTN_FUSED_PREFILL_OVERLAP_WORKERS}"
echo "[INFO] RETRIEVALATTN_Q_BLOCK=${RETRIEVALATTN_Q_BLOCK}"
echo "[INFO] RETRIEVALATTN_K_BLOCK=${RETRIEVALATTN_K_BLOCK}"
echo "[INFO] RETRIEVALATTN_OVERLAP=${RETRIEVALATTN_OVERLAP}"
echo "[INFO] RETRIEVALATTN_LAYER_GPU_CACHE=${RETRIEVALATTN_LAYER_GPU_CACHE}"
echo "[INFO] RETRIEVALATTN_DECODE_INDEX=${RETRIEVALATTN_DECODE_INDEX}"
echo "[INFO] RETRIEVALATTN_SEED_MODE=${RETRIEVALATTN_SEED_MODE}"
echo "[INFO] RETRIEVALATTN_QUERY_MODE=${RETRIEVALATTN_QUERY_MODE}"
echo "[INFO] RETRIEVALATTN_SCORE_MODE=${RETRIEVALATTN_SCORE_MODE}"
echo "[INFO] RETRIEVALATTN_GRAPH_BUILDER=${RETRIEVALATTN_GRAPH_BUILDER}"
echo "[INFO] RETRIEVALATTN_ROAR_NQ=${RETRIEVALATTN_ROAR_NQ}"
echo "[INFO] RETRIEVALATTN_ROAR_L=${RETRIEVALATTN_ROAR_L}"
echo "[INFO] RETRIEVALATTN_ROAR_M=${RETRIEVALATTN_ROAR_M}"
echo "[INFO] RETRIEVALATTN_ROAR_ENABLE_ENHANCE=${RETRIEVALATTN_ROAR_ENABLE_ENHANCE}"
echo "[INFO] RETRIEVALATTN_ROAR_ENHANCE_L=${RETRIEVALATTN_ROAR_ENHANCE_L}"
echo "[INFO] RETRIEVALATTN_ROAR_ENTRY=${RETRIEVALATTN_ROAR_ENTRY}"
echo "[INFO] RETRIEVALATTN_ROAR_MAX_QUERY_PER_PIVOT=${RETRIEVALATTN_ROAR_MAX_QUERY_PER_PIVOT}"
echo "[INFO] RETRIEVALATTN_ROAR_LOG=${RETRIEVALATTN_ROAR_LOG}"
echo "[INFO] RETRIEVALATTN_GRAPH_EXPAND=${RETRIEVALATTN_GRAPH_EXPAND}"
echo "[INFO] RETRIEVALATTN_EXPAND_WIDTH=${RETRIEVALATTN_EXPAND_WIDTH}"
echo "[INFO] RETRIEVALATTN_MIN_VISITS=${RETRIEVALATTN_MIN_VISITS}"
echo "[INFO] RETRIEVALATTN_MAX_VISITS=${RETRIEVALATTN_MAX_VISITS}"
echo "[INFO] RETRIEVALATTN_STOP_PATIENCE=${RETRIEVALATTN_STOP_PATIENCE}"
echo "[INFO] RETRIEVALATTN_STOP_MARGIN=${RETRIEVALATTN_STOP_MARGIN}"
echo "[INFO] RETRIEVALATTN_FRONTIER_TOPN=${RETRIEVALATTN_FRONTIER_TOPN}"
echo "[INFO] RETRIEVALATTN_RERANK=${RETRIEVALATTN_RERANK}"
echo "[INFO] RETRIEVALATTN_RERANK_AGG=${RETRIEVALATTN_RERANK_AGG}"
echo "[INFO] RETRIEVALATTN_SEED_RATIO=${RETRIEVALATTN_SEED_RATIO}"
echo "[INFO] RETRIEVALATTN_CAND_MULT=${RETRIEVALATTN_CAND_MULT}"
echo "[INFO] RETRIEVALATTN_SEED_K_MULT=${RETRIEVALATTN_SEED_K_MULT}"
echo "[INFO] RETRIEVALATTN_SEED_PREV_K=${RETRIEVALATTN_SEED_PREV_K}"
echo "[INFO] RETRIEVALATTN_SEED_HUB_K=${RETRIEVALATTN_SEED_HUB_K}"
echo "[INFO] RETRIEVALATTN_SEED_TAIL_K=${RETRIEVALATTN_SEED_TAIL_K}"
echo "[INFO] RETRIEVALATTN_DEBUG=${RETRIEVALATTN_DEBUG}"
echo "[INFO] RETRIEVALATTN_ASSERT_NONEMPTY=${RETRIEVALATTN_ASSERT_NONEMPTY}"
echo "[INFO] RETRIEVALATTN_VALIDATE_PARITY=${RETRIEVALATTN_VALIDATE_PARITY}"
echo "[INFO] RETRIEVALATTN_DECODE_PROFILE=${RETRIEVALATTN_DECODE_PROFILE}"
echo "[INFO] Python: $(which python)"
python -V
python - <<'PY'
import torch
print("[INFO] torch version:", torch.__version__)
print("[INFO] torch file:", torch.__file__)
PY

if command -v nvidia-smi >/dev/null 2>&1; then
  echo "[INFO] nvidia-smi (before)"
  nvidia-smi
fi

TOKEN_BUDGET_ARGS=()
if [ -n "${TOKEN_BUDGET_OVERRIDE}" ]; then
  TOKEN_BUDGET_ARGS+=(--token_budget_override "${TOKEN_BUDGET_OVERRIDE}")
fi

if [ "${TEST_MODE}" = "simple" ]; then
  echo "[INFO] Running simple_test.py"
  LOW_CPU_MEM_USAGE="${LOW_CPU_MEM_USAGE}" \
  RETRIEVALATTN_GPU_TOPK="${RETRIEVALATTN_GPU_TOPK}" \
  RETRIEVALATTN_CUSTOM_QK_TOPK="${RETRIEVALATTN_CUSTOM_QK_TOPK}" \
  RETRIEVALATTN_CUSTOM_QK_TOPK_BLOCK_Q="${RETRIEVALATTN_CUSTOM_QK_TOPK_BLOCK_Q}" \
  RETRIEVALATTN_CUSTOM_QK_TOPK_LAUNCH_Q_CHUNK="${RETRIEVALATTN_CUSTOM_QK_TOPK_LAUNCH_Q_CHUNK}" \
  RETRIEVALATTN_CUSTOM_QK_TOPK_BLOCK_D="${RETRIEVALATTN_CUSTOM_QK_TOPK_BLOCK_D}" \
  RETRIEVALATTN_CUSTOM_QK_TOPK_BLOCK_K="${RETRIEVALATTN_CUSTOM_QK_TOPK_BLOCK_K}" \
  RETRIEVALATTN_FA_FUSED_PREFILL="${RETRIEVALATTN_FA_FUSED_PREFILL}" \
  RETRIEVALATTN_FA_SHADOW_COMPARE="${RETRIEVALATTN_FA_SHADOW_COMPARE}" \
  RETRIEVALATTN_FA_SHADOW_SAMPLE="${RETRIEVALATTN_FA_SHADOW_SAMPLE}" \
  RETRIEVALATTN_FUSED_PREFILL_OVERLAP="${RETRIEVALATTN_FUSED_PREFILL_OVERLAP}" \
  RETRIEVALATTN_FUSED_PREFILL_OVERLAP_WORKERS="${RETRIEVALATTN_FUSED_PREFILL_OVERLAP_WORKERS}" \
  RETRIEVALATTN_Q_BLOCK="${RETRIEVALATTN_Q_BLOCK}" \
  RETRIEVALATTN_K_BLOCK="${RETRIEVALATTN_K_BLOCK}" \
  RETRIEVALATTN_OVERLAP="${RETRIEVALATTN_OVERLAP}" \
  RETRIEVALATTN_LAYER_GPU_CACHE="${RETRIEVALATTN_LAYER_GPU_CACHE}" \
  RETRIEVALATTN_DECODE_INDEX="${RETRIEVALATTN_DECODE_INDEX}" \
  RETRIEVALATTN_SEED_MODE="${RETRIEVALATTN_SEED_MODE}" \
  RETRIEVALATTN_QUERY_MODE="${RETRIEVALATTN_QUERY_MODE}" \
  RETRIEVALATTN_SCORE_MODE="${RETRIEVALATTN_SCORE_MODE}" \
  RETRIEVALATTN_GRAPH_BUILDER="${RETRIEVALATTN_GRAPH_BUILDER}" \
  RETRIEVALATTN_ROAR_NQ="${RETRIEVALATTN_ROAR_NQ}" \
  RETRIEVALATTN_ROAR_L="${RETRIEVALATTN_ROAR_L}" \
  RETRIEVALATTN_ROAR_M="${RETRIEVALATTN_ROAR_M}" \
  RETRIEVALATTN_ROAR_ENABLE_ENHANCE="${RETRIEVALATTN_ROAR_ENABLE_ENHANCE}" \
  RETRIEVALATTN_ROAR_ENHANCE_L="${RETRIEVALATTN_ROAR_ENHANCE_L}" \
  RETRIEVALATTN_ROAR_ENTRY="${RETRIEVALATTN_ROAR_ENTRY}" \
  RETRIEVALATTN_ROAR_MAX_QUERY_PER_PIVOT="${RETRIEVALATTN_ROAR_MAX_QUERY_PER_PIVOT}" \
  RETRIEVALATTN_ROAR_LOG="${RETRIEVALATTN_ROAR_LOG}" \
  RETRIEVALATTN_GRAPH_EXPAND="${RETRIEVALATTN_GRAPH_EXPAND}" \
  RETRIEVALATTN_EXPAND_WIDTH="${RETRIEVALATTN_EXPAND_WIDTH}" \
  RETRIEVALATTN_MIN_VISITS="${RETRIEVALATTN_MIN_VISITS}" \
  RETRIEVALATTN_MAX_VISITS="${RETRIEVALATTN_MAX_VISITS}" \
  RETRIEVALATTN_STOP_PATIENCE="${RETRIEVALATTN_STOP_PATIENCE}" \
  RETRIEVALATTN_STOP_MARGIN="${RETRIEVALATTN_STOP_MARGIN}" \
  RETRIEVALATTN_FRONTIER_TOPN="${RETRIEVALATTN_FRONTIER_TOPN}" \
  RETRIEVALATTN_RERANK="${RETRIEVALATTN_RERANK}" \
  RETRIEVALATTN_RERANK_AGG="${RETRIEVALATTN_RERANK_AGG}" \
  RETRIEVALATTN_SEED_RATIO="${RETRIEVALATTN_SEED_RATIO}" \
  RETRIEVALATTN_CAND_MULT="${RETRIEVALATTN_CAND_MULT}" \
  RETRIEVALATTN_SEED_K_MULT="${RETRIEVALATTN_SEED_K_MULT}" \
  RETRIEVALATTN_SEED_PREV_K="${RETRIEVALATTN_SEED_PREV_K}" \
  RETRIEVALATTN_SEED_HUB_K="${RETRIEVALATTN_SEED_HUB_K}" \
  RETRIEVALATTN_SEED_TAIL_K="${RETRIEVALATTN_SEED_TAIL_K}" \
  RETRIEVALATTN_DEBUG="${RETRIEVALATTN_DEBUG}" \
  RETRIEVALATTN_ASSERT_NONEMPTY="${RETRIEVALATTN_ASSERT_NONEMPTY}" \
  RETRIEVALATTN_VALIDATE_PARITY="${RETRIEVALATTN_VALIDATE_PARITY}" \
  RETRIEVALATTN_DECODE_PROFILE="${RETRIEVALATTN_DECODE_PROFILE}" \
  /usr/bin/time -v python -u simple_test.py \
    --model_name "${MODEL_NAME}" \
    --attn_type "${ATTN_TYPE}" \
    --dtype "${DTYPE}" \
    --batch_size "${BATCH_SIZE}" \
    --gen_len "${GEN_LEN}" \
    "${TOKEN_BUDGET_ARGS[@]}"
elif [ "${TEST_MODE}" = "throughput" ]; then
  echo "[INFO] Running throughput_eval/test.py"
  LOW_CPU_MEM_USAGE="${LOW_CPU_MEM_USAGE}" \
  RETRIEVALATTN_GPU_TOPK="${RETRIEVALATTN_GPU_TOPK}" \
  RETRIEVALATTN_CUSTOM_QK_TOPK="${RETRIEVALATTN_CUSTOM_QK_TOPK}" \
  RETRIEVALATTN_CUSTOM_QK_TOPK_BLOCK_Q="${RETRIEVALATTN_CUSTOM_QK_TOPK_BLOCK_Q}" \
  RETRIEVALATTN_CUSTOM_QK_TOPK_LAUNCH_Q_CHUNK="${RETRIEVALATTN_CUSTOM_QK_TOPK_LAUNCH_Q_CHUNK}" \
  RETRIEVALATTN_CUSTOM_QK_TOPK_BLOCK_D="${RETRIEVALATTN_CUSTOM_QK_TOPK_BLOCK_D}" \
  RETRIEVALATTN_CUSTOM_QK_TOPK_BLOCK_K="${RETRIEVALATTN_CUSTOM_QK_TOPK_BLOCK_K}" \
  RETRIEVALATTN_FA_FUSED_PREFILL="${RETRIEVALATTN_FA_FUSED_PREFILL}" \
  RETRIEVALATTN_FA_SHADOW_COMPARE="${RETRIEVALATTN_FA_SHADOW_COMPARE}" \
  RETRIEVALATTN_FA_SHADOW_SAMPLE="${RETRIEVALATTN_FA_SHADOW_SAMPLE}" \
  RETRIEVALATTN_FUSED_PREFILL_OVERLAP="${RETRIEVALATTN_FUSED_PREFILL_OVERLAP}" \
  RETRIEVALATTN_FUSED_PREFILL_OVERLAP_WORKERS="${RETRIEVALATTN_FUSED_PREFILL_OVERLAP_WORKERS}" \
  RETRIEVALATTN_Q_BLOCK="${RETRIEVALATTN_Q_BLOCK}" \
  RETRIEVALATTN_K_BLOCK="${RETRIEVALATTN_K_BLOCK}" \
  RETRIEVALATTN_OVERLAP="${RETRIEVALATTN_OVERLAP}" \
  RETRIEVALATTN_LAYER_GPU_CACHE="${RETRIEVALATTN_LAYER_GPU_CACHE}" \
  RETRIEVALATTN_DECODE_INDEX="${RETRIEVALATTN_DECODE_INDEX}" \
  RETRIEVALATTN_SEED_MODE="${RETRIEVALATTN_SEED_MODE}" \
  RETRIEVALATTN_QUERY_MODE="${RETRIEVALATTN_QUERY_MODE}" \
  RETRIEVALATTN_SCORE_MODE="${RETRIEVALATTN_SCORE_MODE}" \
  RETRIEVALATTN_GRAPH_BUILDER="${RETRIEVALATTN_GRAPH_BUILDER}" \
  RETRIEVALATTN_ROAR_NQ="${RETRIEVALATTN_ROAR_NQ}" \
  RETRIEVALATTN_ROAR_L="${RETRIEVALATTN_ROAR_L}" \
  RETRIEVALATTN_ROAR_M="${RETRIEVALATTN_ROAR_M}" \
  RETRIEVALATTN_ROAR_ENABLE_ENHANCE="${RETRIEVALATTN_ROAR_ENABLE_ENHANCE}" \
  RETRIEVALATTN_ROAR_ENHANCE_L="${RETRIEVALATTN_ROAR_ENHANCE_L}" \
  RETRIEVALATTN_ROAR_ENTRY="${RETRIEVALATTN_ROAR_ENTRY}" \
  RETRIEVALATTN_ROAR_MAX_QUERY_PER_PIVOT="${RETRIEVALATTN_ROAR_MAX_QUERY_PER_PIVOT}" \
  RETRIEVALATTN_ROAR_LOG="${RETRIEVALATTN_ROAR_LOG}" \
  RETRIEVALATTN_GRAPH_EXPAND="${RETRIEVALATTN_GRAPH_EXPAND}" \
  RETRIEVALATTN_EXPAND_WIDTH="${RETRIEVALATTN_EXPAND_WIDTH}" \
  RETRIEVALATTN_MIN_VISITS="${RETRIEVALATTN_MIN_VISITS}" \
  RETRIEVALATTN_MAX_VISITS="${RETRIEVALATTN_MAX_VISITS}" \
  RETRIEVALATTN_STOP_PATIENCE="${RETRIEVALATTN_STOP_PATIENCE}" \
  RETRIEVALATTN_STOP_MARGIN="${RETRIEVALATTN_STOP_MARGIN}" \
  RETRIEVALATTN_FRONTIER_TOPN="${RETRIEVALATTN_FRONTIER_TOPN}" \
  RETRIEVALATTN_RERANK="${RETRIEVALATTN_RERANK}" \
  RETRIEVALATTN_RERANK_AGG="${RETRIEVALATTN_RERANK_AGG}" \
  RETRIEVALATTN_SEED_RATIO="${RETRIEVALATTN_SEED_RATIO}" \
  RETRIEVALATTN_CAND_MULT="${RETRIEVALATTN_CAND_MULT}" \
  RETRIEVALATTN_SEED_K_MULT="${RETRIEVALATTN_SEED_K_MULT}" \
  RETRIEVALATTN_SEED_PREV_K="${RETRIEVALATTN_SEED_PREV_K}" \
  RETRIEVALATTN_SEED_HUB_K="${RETRIEVALATTN_SEED_HUB_K}" \
  RETRIEVALATTN_SEED_TAIL_K="${RETRIEVALATTN_SEED_TAIL_K}" \
  RETRIEVALATTN_DEBUG="${RETRIEVALATTN_DEBUG}" \
  RETRIEVALATTN_ASSERT_NONEMPTY="${RETRIEVALATTN_ASSERT_NONEMPTY}" \
  RETRIEVALATTN_VALIDATE_PARITY="${RETRIEVALATTN_VALIDATE_PARITY}" \
  RETRIEVALATTN_DECODE_PROFILE="${RETRIEVALATTN_DECODE_PROFILE}" \
  /usr/bin/time -v python -u throughput_eval/test.py \
    --model_name "${MODEL_NAME}" \
    --attn_type "${ATTN_TYPE}" \
    --dtype "${DTYPE}" \
    --batch_size "${BATCH_SIZE}" \
    --task_name vt \
    "${TOKEN_BUDGET_ARGS[@]}"
else
  echo "[ERROR] Unknown TEST_MODE: ${TEST_MODE}"
  exit 1
fi

if command -v nvidia-smi >/dev/null 2>&1; then
  echo "[INFO] nvidia-smi (after)"
  nvidia-smi
fi

echo "[INFO] Job finished at: $(date)"
