#!/bin/bash
#SBATCH --job-name=test
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=48000m
#SBATCH --time=60:00
#SBATCH --account=zhengya98
#SBATCH --partition=spgpu
#SBATCH --gpus-per-node=1

module purge
module load python/3.10.4
module unload pytorch 2>/dev/null || true
module load cuda/12.8.1

if [ -f ".venv/bin/activate" ]; then
  # shellcheck disable=SC1091
  source .venv/bin/activate
else
  echo "[ERROR] .venv/bin/activate not found. Did you run install.sh?"
  exit 1
fi

unset PYTHONPATH
unset PYTHONHOME
export PYTHONNOUSERSITE=1

set -euo pipefail

echo "[INFO] Job started at: $(date)"
echo "[INFO] Host: $(hostname)"

TEST_MODE="${TEST_MODE:-simple}"
ATTN_TYPE="${ATTN_TYPE:-RetrievalAttention}"
MODEL_NAME="${MODEL_NAME:-meta-llama/Llama-3.1-8B-Instruct}"
DTYPE="${DTYPE:-bf16}"
BATCH_SIZE="${BATCH_SIZE:-1}"
GEN_LEN="${GEN_LEN:-100}"
RECALL_ONLY="${RECALL_ONLY:-0}"
RECALL_INPUT_TOKENS="${RECALL_INPUT_TOKENS:-8192}"
RECALL_MIN_RECALL="${RECALL_MIN_RECALL:-}"
LOW_CPU_MEM_USAGE="${LOW_CPU_MEM_USAGE:-1}"
TOKEN_BUDGET_OVERRIDE="${TOKEN_BUDGET_OVERRIDE:-100}"

# Fused-only RetrievalAttention runtime.
RETRIEVALATTN_FA_FUSED_PREFILL=1
RETRIEVALATTN_FA_GRAPH_FUSED="${RETRIEVALATTN_FA_GRAPH_FUSED:-0}"
RETRIEVALATTN_FA_GRAPH_FUSED_REQUIRE="${RETRIEVALATTN_FA_GRAPH_FUSED_REQUIRE:-0}"
RETRIEVALATTN_FA_GRAPH_FUSED_CHECK="${RETRIEVALATTN_FA_GRAPH_FUSED_CHECK:-1}"
RETRIEVALATTN_FA_GRAPH_FUSED_QUALITY_FLOOR="${RETRIEVALATTN_FA_GRAPH_FUSED_QUALITY_FLOOR:-0.90}"
RETRIEVALATTN_FA_GRAPH_PROFILE="${RETRIEVALATTN_FA_GRAPH_PROFILE:-0}"
RETRIEVALATTN_FA_GRAPH_DEBUG="${RETRIEVALATTN_FA_GRAPH_DEBUG:-0}"
RETRIEVALATTN_FA_KERNEL_PROFILE="${RETRIEVALATTN_FA_KERNEL_PROFILE:-0}"
RETRIEVALATTN_FA_KERNEL_DEBUG="${RETRIEVALATTN_FA_KERNEL_DEBUG:-0}"
RETRIEVALATTN_FA_TOPK_BATCHED="${RETRIEVALATTN_FA_TOPK_BATCHED:-0}"
RETRIEVALATTN_FA_KERNEL_MODE="${RETRIEVALATTN_FA_KERNEL_MODE:-v2_splitk}"
RETRIEVALATTN_FA_SPLITK="${RETRIEVALATTN_FA_SPLITK:-auto}"
RETRIEVALATTN_FA_MERGE_KERNEL="${RETRIEVALATTN_FA_MERGE_KERNEL:-1}"
RETRIEVALATTN_FA_FORCE_PYTHON_TOPK="${RETRIEVALATTN_FA_FORCE_PYTHON_TOPK:-0}"
RETRIEVALATTN_FUSED_PREFILL_OVERLAP="${RETRIEVALATTN_FUSED_PREFILL_OVERLAP:-1}"
RETRIEVALATTN_FUSED_PREFILL_OVERLAP_WORKERS="${RETRIEVALATTN_FUSED_PREFILL_OVERLAP_WORKERS:-1}"
RETRIEVALATTN_DECODE_INDEX="${RETRIEVALATTN_DECODE_INDEX:-faiss}"
RETRIEVALATTN_SEED_MODE="${RETRIEVALATTN_SEED_MODE:-graph_only}"
RETRIEVALATTN_QUERY_MODE="${RETRIEVALATTN_QUERY_MODE:-per_head}"
RETRIEVALATTN_SCORE_MODE="${RETRIEVALATTN_SCORE_MODE:-ip}"
RETRIEVALATTN_ROAR_NQ="${RETRIEVALATTN_ROAR_NQ:-8}"
RETRIEVALATTN_ROAR_L="${RETRIEVALATTN_ROAR_L:-4}"
RETRIEVALATTN_ROAR_M="${RETRIEVALATTN_ROAR_M:-8}"
RETRIEVALATTN_ROAR_ENABLE_ENHANCE="${RETRIEVALATTN_ROAR_ENABLE_ENHANCE:-1}"
RETRIEVALATTN_ROAR_ENHANCE_L="${RETRIEVALATTN_ROAR_ENHANCE_L:-4}"
RETRIEVALATTN_ROAR_ENTRY="${RETRIEVALATTN_ROAR_ENTRY:-hub}"
RETRIEVALATTN_ROAR_MAX_QUERY_PER_PIVOT="${RETRIEVALATTN_ROAR_MAX_QUERY_PER_PIVOT:-0}"
RETRIEVALATTN_ROAR_LOG="${RETRIEVALATTN_ROAR_LOG:-1}"
RETRIEVALATTN_ROAR_BACKEND="${RETRIEVALATTN_ROAR_BACKEND:-cpp}"
RETRIEVALATTN_ROAR_CPP_THREADS="${RETRIEVALATTN_ROAR_CPP_THREADS:-${SLURM_CPUS_PER_TASK:-0}}"
RETRIEVALATTN_ROAR_PY_GPU_DEVICE="${RETRIEVALATTN_ROAR_PY_GPU_DEVICE:-cuda}"
RETRIEVALATTN_ROAR_PY_GPU_BATCH="${RETRIEVALATTN_ROAR_PY_GPU_BATCH:-256}"
RETRIEVALATTN_GRAPH_EXPAND="${RETRIEVALATTN_GRAPH_EXPAND:-1}"
RETRIEVALATTN_EXPAND_WIDTH="${RETRIEVALATTN_EXPAND_WIDTH:-48}"
RETRIEVALATTN_MIN_VISITS="${RETRIEVALATTN_MIN_VISITS:-96}"
RETRIEVALATTN_MAX_VISITS="${RETRIEVALATTN_MAX_VISITS:-2048}"
RETRIEVALATTN_STOP_PATIENCE="${RETRIEVALATTN_STOP_PATIENCE:-1}"
RETRIEVALATTN_STOP_MARGIN="${RETRIEVALATTN_STOP_MARGIN:-0.001}"
RETRIEVALATTN_FRONTIER_TOPN="${RETRIEVALATTN_FRONTIER_TOPN:-0}"
RETRIEVALATTN_RERANK="${RETRIEVALATTN_RERANK:-1}"
RETRIEVALATTN_RERANK_AGG="${RETRIEVALATTN_RERANK_AGG:-max}"
RETRIEVALATTN_SEED_RATIO="${RETRIEVALATTN_SEED_RATIO:-0.7}"
RETRIEVALATTN_CAND_MULT="${RETRIEVALATTN_CAND_MULT:-4}"
RETRIEVALATTN_SEED_K_MULT="${RETRIEVALATTN_SEED_K_MULT:-1}"
RETRIEVALATTN_SEED_PREV_K="${RETRIEVALATTN_SEED_PREV_K:-256}"
RETRIEVALATTN_SEED_HUB_K="${RETRIEVALATTN_SEED_HUB_K:-64}"
RETRIEVALATTN_SEED_TAIL_K="${RETRIEVALATTN_SEED_TAIL_K:-32}"
RETRIEVALATTN_DEBUG="${RETRIEVALATTN_DEBUG:-0}"
RETRIEVALATTN_ASSERT_NONEMPTY="${RETRIEVALATTN_ASSERT_NONEMPTY:-0}"
RETRIEVALATTN_VALIDATE_PARITY="${RETRIEVALATTN_VALIDATE_PARITY:-0}"
RETRIEVALATTN_PARITY_LAYERS="${RETRIEVALATTN_PARITY_LAYERS:-1}"
RETRIEVALATTN_PARITY_HEADS="${RETRIEVALATTN_PARITY_HEADS:-1}"
RETRIEVALATTN_PARITY_SAMPLE="${RETRIEVALATTN_PARITY_SAMPLE:-256}"
RETRIEVALATTN_GRAPH_TRAIN_FRAC="${RETRIEVALATTN_GRAPH_TRAIN_FRAC:-1.0}"
RETRIEVALATTN_GRAPH_SPLIT="${RETRIEVALATTN_GRAPH_SPLIT:-stratified}"
RETRIEVALATTN_GRAPH_SPLIT_SEED="${RETRIEVALATTN_GRAPH_SPLIT_SEED:-1234}"
RETRIEVALATTN_PARITY_HOLDOUT_ONLY="${RETRIEVALATTN_PARITY_HOLDOUT_ONLY:-0}"
RETRIEVALATTN_TRAVERSAL_EVAL="${RETRIEVALATTN_TRAVERSAL_EVAL:-0}"
RETRIEVALATTN_TRAVERSAL_EVAL_SAMPLE="${RETRIEVALATTN_TRAVERSAL_EVAL_SAMPLE:-64}"
RETRIEVALATTN_DECODE_PROFILE="${RETRIEVALATTN_DECODE_PROFILE:-1}"

echo "[INFO] TEST_MODE=${TEST_MODE}"
echo "[INFO] ATTN_TYPE=${ATTN_TYPE}"
echo "[INFO] MODEL_NAME=${MODEL_NAME}"
echo "[INFO] DTYPE=${DTYPE}"
echo "[INFO] BATCH_SIZE=${BATCH_SIZE}"
echo "[INFO] GEN_LEN=${GEN_LEN}"
echo "[INFO] RECALL_ONLY=${RECALL_ONLY}"
echo "[INFO] RECALL_INPUT_TOKENS=${RECALL_INPUT_TOKENS}"
echo "[INFO] RECALL_MIN_RECALL=${RECALL_MIN_RECALL}"
echo "[INFO] LOW_CPU_MEM_USAGE=${LOW_CPU_MEM_USAGE}"
echo "[INFO] TOKEN_BUDGET_OVERRIDE=${TOKEN_BUDGET_OVERRIDE}"
echo "[INFO] RETRIEVALATTN_FA_FUSED_PREFILL=${RETRIEVALATTN_FA_FUSED_PREFILL}"
echo "[INFO] RETRIEVALATTN_FA_GRAPH_FUSED=${RETRIEVALATTN_FA_GRAPH_FUSED}"
echo "[INFO] RETRIEVALATTN_FA_GRAPH_FUSED_REQUIRE=${RETRIEVALATTN_FA_GRAPH_FUSED_REQUIRE}"
echo "[INFO] RETRIEVALATTN_FA_GRAPH_FUSED_CHECK=${RETRIEVALATTN_FA_GRAPH_FUSED_CHECK}"
echo "[INFO] RETRIEVALATTN_FA_GRAPH_FUSED_QUALITY_FLOOR=${RETRIEVALATTN_FA_GRAPH_FUSED_QUALITY_FLOOR}"
echo "[INFO] RETRIEVALATTN_FA_GRAPH_PROFILE=${RETRIEVALATTN_FA_GRAPH_PROFILE}"
echo "[INFO] RETRIEVALATTN_FA_GRAPH_DEBUG=${RETRIEVALATTN_FA_GRAPH_DEBUG}"
echo "[INFO] RETRIEVALATTN_FA_KERNEL_PROFILE=${RETRIEVALATTN_FA_KERNEL_PROFILE}"
echo "[INFO] RETRIEVALATTN_FA_KERNEL_DEBUG=${RETRIEVALATTN_FA_KERNEL_DEBUG}"
echo "[INFO] RETRIEVALATTN_FA_TOPK_BATCHED=${RETRIEVALATTN_FA_TOPK_BATCHED}"
echo "[INFO] RETRIEVALATTN_FA_KERNEL_MODE=${RETRIEVALATTN_FA_KERNEL_MODE}"
echo "[INFO] RETRIEVALATTN_FA_SPLITK=${RETRIEVALATTN_FA_SPLITK}"
echo "[INFO] RETRIEVALATTN_FA_MERGE_KERNEL=${RETRIEVALATTN_FA_MERGE_KERNEL}"
echo "[INFO] RETRIEVALATTN_FA_FORCE_PYTHON_TOPK=${RETRIEVALATTN_FA_FORCE_PYTHON_TOPK}"
echo "[INFO] RETRIEVALATTN_FUSED_PREFILL_OVERLAP=${RETRIEVALATTN_FUSED_PREFILL_OVERLAP}"
echo "[INFO] RETRIEVALATTN_FUSED_PREFILL_OVERLAP_WORKERS=${RETRIEVALATTN_FUSED_PREFILL_OVERLAP_WORKERS}"
echo "[INFO] RETRIEVALATTN_DECODE_INDEX=${RETRIEVALATTN_DECODE_INDEX}"
echo "[INFO] RETRIEVALATTN_SEED_MODE=${RETRIEVALATTN_SEED_MODE}"
echo "[INFO] RETRIEVALATTN_QUERY_MODE=${RETRIEVALATTN_QUERY_MODE}"
echo "[INFO] RETRIEVALATTN_SCORE_MODE=${RETRIEVALATTN_SCORE_MODE}"
echo "[INFO] RETRIEVALATTN_ROAR_NQ=${RETRIEVALATTN_ROAR_NQ}"
echo "[INFO] RETRIEVALATTN_ROAR_L=${RETRIEVALATTN_ROAR_L}"
echo "[INFO] RETRIEVALATTN_ROAR_M=${RETRIEVALATTN_ROAR_M}"
echo "[INFO] RETRIEVALATTN_ROAR_ENABLE_ENHANCE=${RETRIEVALATTN_ROAR_ENABLE_ENHANCE}"
echo "[INFO] RETRIEVALATTN_ROAR_ENHANCE_L=${RETRIEVALATTN_ROAR_ENHANCE_L}"
echo "[INFO] RETRIEVALATTN_ROAR_ENTRY=${RETRIEVALATTN_ROAR_ENTRY}"
echo "[INFO] RETRIEVALATTN_ROAR_MAX_QUERY_PER_PIVOT=${RETRIEVALATTN_ROAR_MAX_QUERY_PER_PIVOT}"
echo "[INFO] RETRIEVALATTN_ROAR_LOG=${RETRIEVALATTN_ROAR_LOG}"
echo "[INFO] RETRIEVALATTN_ROAR_BACKEND=${RETRIEVALATTN_ROAR_BACKEND}"
echo "[INFO] RETRIEVALATTN_ROAR_CPP_THREADS=${RETRIEVALATTN_ROAR_CPP_THREADS}"
echo "[INFO] RETRIEVALATTN_ROAR_PY_GPU_DEVICE=${RETRIEVALATTN_ROAR_PY_GPU_DEVICE}"
echo "[INFO] RETRIEVALATTN_ROAR_PY_GPU_BATCH=${RETRIEVALATTN_ROAR_PY_GPU_BATCH}"
echo "[INFO] RETRIEVALATTN_GRAPH_EXPAND=${RETRIEVALATTN_GRAPH_EXPAND}"
echo "[INFO] RETRIEVALATTN_EXPAND_WIDTH=${RETRIEVALATTN_EXPAND_WIDTH}"
echo "[INFO] RETRIEVALATTN_MIN_VISITS=${RETRIEVALATTN_MIN_VISITS}"
echo "[INFO] RETRIEVALATTN_MAX_VISITS=${RETRIEVALATTN_MAX_VISITS}"
echo "[INFO] RETRIEVALATTN_STOP_PATIENCE=${RETRIEVALATTN_STOP_PATIENCE}"
echo "[INFO] RETRIEVALATTN_STOP_MARGIN=${RETRIEVALATTN_STOP_MARGIN}"
echo "[INFO] RETRIEVALATTN_FRONTIER_TOPN=${RETRIEVALATTN_FRONTIER_TOPN}"
echo "[INFO] RETRIEVALATTN_RERANK=${RETRIEVALATTN_RERANK}"
echo "[INFO] RETRIEVALATTN_RERANK_AGG=${RETRIEVALATTN_RERANK_AGG}"
echo "[INFO] RETRIEVALATTN_SEED_RATIO=${RETRIEVALATTN_SEED_RATIO}"
echo "[INFO] RETRIEVALATTN_CAND_MULT=${RETRIEVALATTN_CAND_MULT}"
echo "[INFO] RETRIEVALATTN_SEED_K_MULT=${RETRIEVALATTN_SEED_K_MULT}"
echo "[INFO] RETRIEVALATTN_SEED_PREV_K=${RETRIEVALATTN_SEED_PREV_K}"
echo "[INFO] RETRIEVALATTN_SEED_HUB_K=${RETRIEVALATTN_SEED_HUB_K}"
echo "[INFO] RETRIEVALATTN_SEED_TAIL_K=${RETRIEVALATTN_SEED_TAIL_K}"
echo "[INFO] RETRIEVALATTN_DEBUG=${RETRIEVALATTN_DEBUG}"
echo "[INFO] RETRIEVALATTN_ASSERT_NONEMPTY=${RETRIEVALATTN_ASSERT_NONEMPTY}"
echo "[INFO] RETRIEVALATTN_VALIDATE_PARITY=${RETRIEVALATTN_VALIDATE_PARITY}"
echo "[INFO] RETRIEVALATTN_PARITY_LAYERS=${RETRIEVALATTN_PARITY_LAYERS}"
echo "[INFO] RETRIEVALATTN_PARITY_HEADS=${RETRIEVALATTN_PARITY_HEADS}"
echo "[INFO] RETRIEVALATTN_PARITY_SAMPLE=${RETRIEVALATTN_PARITY_SAMPLE}"
echo "[INFO] RETRIEVALATTN_GRAPH_TRAIN_FRAC=${RETRIEVALATTN_GRAPH_TRAIN_FRAC}"
echo "[INFO] RETRIEVALATTN_GRAPH_SPLIT=${RETRIEVALATTN_GRAPH_SPLIT}"
echo "[INFO] RETRIEVALATTN_GRAPH_SPLIT_SEED=${RETRIEVALATTN_GRAPH_SPLIT_SEED}"
echo "[INFO] RETRIEVALATTN_PARITY_HOLDOUT_ONLY=${RETRIEVALATTN_PARITY_HOLDOUT_ONLY}"
echo "[INFO] RETRIEVALATTN_TRAVERSAL_EVAL=${RETRIEVALATTN_TRAVERSAL_EVAL}"
echo "[INFO] RETRIEVALATTN_TRAVERSAL_EVAL_SAMPLE=${RETRIEVALATTN_TRAVERSAL_EVAL_SAMPLE}"
echo "[INFO] RETRIEVALATTN_DECODE_PROFILE=${RETRIEVALATTN_DECODE_PROFILE}"
echo "[INFO] Python: $(which python)"
python -V
python - <<'PY'
import torch
print("[INFO] torch version:", torch.__version__)
print("[INFO] torch file:", torch.__file__)
PY

python - <<'PY'
import os
import sys
from pathlib import Path

submit_dir = Path(os.environ.get("SLURM_SUBMIT_DIR", os.getcwd()))
ext_dir = (submit_dir / "third_party" / "RoarGraph" / "python_ext").resolve()
if str(ext_dir) not in sys.path:
    sys.path.insert(0, str(ext_dir))
try:
    import roargraph_builder_ext  # noqa: F401
    print(f"[INFO] RoarGraph C++ extension import OK from: {ext_dir}")
except Exception as exc:
    print("[ERROR] RoarGraph C++ extension import failed.")
    print("[ERROR] Build it with:")
    print("[ERROR]   module load python/3.10.4")
    print("[ERROR]   source .venv/bin/activate")
    print("[ERROR]   python third_party/RoarGraph/python_ext/setup.py build_ext --inplace")
    print(f"[ERROR] Import error: {exc}")
    raise SystemExit(2)
PY

if command -v nvidia-smi >/dev/null 2>&1; then
  echo "[INFO] nvidia-smi (before)"
  nvidia-smi
fi

TOKEN_BUDGET_ARGS=()
if [ -n "${TOKEN_BUDGET_OVERRIDE}" ]; then
  TOKEN_BUDGET_ARGS+=(--token_budget_override "${TOKEN_BUDGET_OVERRIDE}")
fi

RECALL_ARGS=()
if [ "${RECALL_ONLY}" = "1" ]; then
  if [ "${RETRIEVALATTN_VALIDATE_PARITY}" != "1" ]; then
    echo "[INFO] RECALL_ONLY=1 -> forcing RETRIEVALATTN_VALIDATE_PARITY=1"
    RETRIEVALATTN_VALIDATE_PARITY=1
  fi
  if [ "${RETRIEVALATTN_TRAVERSAL_EVAL}" != "1" ]; then
    echo "[INFO] RECALL_ONLY=1 -> forcing RETRIEVALATTN_TRAVERSAL_EVAL=1"
    RETRIEVALATTN_TRAVERSAL_EVAL=1
  fi
  RECALL_ARGS+=(--recall_only --recall_input_tokens "${RECALL_INPUT_TOKENS}")
  if [ -n "${RECALL_MIN_RECALL}" ]; then
    RECALL_ARGS+=(--recall_min_recall "${RECALL_MIN_RECALL}")
  fi
fi

if [ "${TEST_MODE}" = "simple" ]; then
  echo "[INFO] Running simple_test.py"
  LOW_CPU_MEM_USAGE="${LOW_CPU_MEM_USAGE}" \
  RETRIEVALATTN_FA_FUSED_PREFILL="${RETRIEVALATTN_FA_FUSED_PREFILL}" \
  RETRIEVALATTN_FA_GRAPH_FUSED="${RETRIEVALATTN_FA_GRAPH_FUSED}" \
  RETRIEVALATTN_FA_GRAPH_FUSED_REQUIRE="${RETRIEVALATTN_FA_GRAPH_FUSED_REQUIRE}" \
  RETRIEVALATTN_FA_GRAPH_FUSED_CHECK="${RETRIEVALATTN_FA_GRAPH_FUSED_CHECK}" \
  RETRIEVALATTN_FA_GRAPH_FUSED_QUALITY_FLOOR="${RETRIEVALATTN_FA_GRAPH_FUSED_QUALITY_FLOOR}" \
  RETRIEVALATTN_FA_GRAPH_PROFILE="${RETRIEVALATTN_FA_GRAPH_PROFILE}" \
  RETRIEVALATTN_FA_GRAPH_DEBUG="${RETRIEVALATTN_FA_GRAPH_DEBUG}" \
  RETRIEVALATTN_FA_KERNEL_PROFILE="${RETRIEVALATTN_FA_KERNEL_PROFILE}" \
  RETRIEVALATTN_FA_KERNEL_DEBUG="${RETRIEVALATTN_FA_KERNEL_DEBUG}" \
  RETRIEVALATTN_FA_TOPK_BATCHED="${RETRIEVALATTN_FA_TOPK_BATCHED}" \
  RETRIEVALATTN_FA_KERNEL_MODE="${RETRIEVALATTN_FA_KERNEL_MODE}" \
  RETRIEVALATTN_FA_SPLITK="${RETRIEVALATTN_FA_SPLITK}" \
  RETRIEVALATTN_FA_MERGE_KERNEL="${RETRIEVALATTN_FA_MERGE_KERNEL}" \
  RETRIEVALATTN_FA_FORCE_PYTHON_TOPK="${RETRIEVALATTN_FA_FORCE_PYTHON_TOPK}" \
  RETRIEVALATTN_FUSED_PREFILL_OVERLAP="${RETRIEVALATTN_FUSED_PREFILL_OVERLAP}" \
  RETRIEVALATTN_FUSED_PREFILL_OVERLAP_WORKERS="${RETRIEVALATTN_FUSED_PREFILL_OVERLAP_WORKERS}" \
  RETRIEVALATTN_DECODE_INDEX="${RETRIEVALATTN_DECODE_INDEX}" \
  RETRIEVALATTN_SEED_MODE="${RETRIEVALATTN_SEED_MODE}" \
  RETRIEVALATTN_QUERY_MODE="${RETRIEVALATTN_QUERY_MODE}" \
  RETRIEVALATTN_SCORE_MODE="${RETRIEVALATTN_SCORE_MODE}" \
  RETRIEVALATTN_ROAR_NQ="${RETRIEVALATTN_ROAR_NQ}" \
  RETRIEVALATTN_ROAR_L="${RETRIEVALATTN_ROAR_L}" \
  RETRIEVALATTN_ROAR_M="${RETRIEVALATTN_ROAR_M}" \
  RETRIEVALATTN_ROAR_ENABLE_ENHANCE="${RETRIEVALATTN_ROAR_ENABLE_ENHANCE}" \
  RETRIEVALATTN_ROAR_ENHANCE_L="${RETRIEVALATTN_ROAR_ENHANCE_L}" \
  RETRIEVALATTN_ROAR_ENTRY="${RETRIEVALATTN_ROAR_ENTRY}" \
  RETRIEVALATTN_ROAR_MAX_QUERY_PER_PIVOT="${RETRIEVALATTN_ROAR_MAX_QUERY_PER_PIVOT}" \
  RETRIEVALATTN_ROAR_LOG="${RETRIEVALATTN_ROAR_LOG}" \
  RETRIEVALATTN_ROAR_BACKEND="${RETRIEVALATTN_ROAR_BACKEND}" \
  RETRIEVALATTN_ROAR_CPP_THREADS="${RETRIEVALATTN_ROAR_CPP_THREADS}" \
  RETRIEVALATTN_ROAR_PY_GPU_DEVICE="${RETRIEVALATTN_ROAR_PY_GPU_DEVICE}" \
  RETRIEVALATTN_ROAR_PY_GPU_BATCH="${RETRIEVALATTN_ROAR_PY_GPU_BATCH}" \
  RETRIEVALATTN_GRAPH_EXPAND="${RETRIEVALATTN_GRAPH_EXPAND}" \
  RETRIEVALATTN_EXPAND_WIDTH="${RETRIEVALATTN_EXPAND_WIDTH}" \
  RETRIEVALATTN_MIN_VISITS="${RETRIEVALATTN_MIN_VISITS}" \
  RETRIEVALATTN_MAX_VISITS="${RETRIEVALATTN_MAX_VISITS}" \
  RETRIEVALATTN_STOP_PATIENCE="${RETRIEVALATTN_STOP_PATIENCE}" \
  RETRIEVALATTN_STOP_MARGIN="${RETRIEVALATTN_STOP_MARGIN}" \
  RETRIEVALATTN_FRONTIER_TOPN="${RETRIEVALATTN_FRONTIER_TOPN}" \
  RETRIEVALATTN_RERANK="${RETRIEVALATTN_RERANK}" \
  RETRIEVALATTN_RERANK_AGG="${RETRIEVALATTN_RERANK_AGG}" \
  RETRIEVALATTN_SEED_RATIO="${RETRIEVALATTN_SEED_RATIO}" \
  RETRIEVALATTN_CAND_MULT="${RETRIEVALATTN_CAND_MULT}" \
  RETRIEVALATTN_SEED_K_MULT="${RETRIEVALATTN_SEED_K_MULT}" \
  RETRIEVALATTN_SEED_PREV_K="${RETRIEVALATTN_SEED_PREV_K}" \
  RETRIEVALATTN_SEED_HUB_K="${RETRIEVALATTN_SEED_HUB_K}" \
  RETRIEVALATTN_SEED_TAIL_K="${RETRIEVALATTN_SEED_TAIL_K}" \
  RETRIEVALATTN_DEBUG="${RETRIEVALATTN_DEBUG}" \
  RETRIEVALATTN_ASSERT_NONEMPTY="${RETRIEVALATTN_ASSERT_NONEMPTY}" \
  RETRIEVALATTN_VALIDATE_PARITY="${RETRIEVALATTN_VALIDATE_PARITY}" \
  RETRIEVALATTN_PARITY_LAYERS="${RETRIEVALATTN_PARITY_LAYERS}" \
  RETRIEVALATTN_PARITY_HEADS="${RETRIEVALATTN_PARITY_HEADS}" \
  RETRIEVALATTN_PARITY_SAMPLE="${RETRIEVALATTN_PARITY_SAMPLE}" \
  RETRIEVALATTN_GRAPH_TRAIN_FRAC="${RETRIEVALATTN_GRAPH_TRAIN_FRAC}" \
  RETRIEVALATTN_GRAPH_SPLIT="${RETRIEVALATTN_GRAPH_SPLIT}" \
  RETRIEVALATTN_GRAPH_SPLIT_SEED="${RETRIEVALATTN_GRAPH_SPLIT_SEED}" \
  RETRIEVALATTN_PARITY_HOLDOUT_ONLY="${RETRIEVALATTN_PARITY_HOLDOUT_ONLY}" \
  RETRIEVALATTN_TRAVERSAL_EVAL="${RETRIEVALATTN_TRAVERSAL_EVAL}" \
  RETRIEVALATTN_TRAVERSAL_EVAL_SAMPLE="${RETRIEVALATTN_TRAVERSAL_EVAL_SAMPLE}" \
  RETRIEVALATTN_DECODE_PROFILE="${RETRIEVALATTN_DECODE_PROFILE}" \
  /usr/bin/time -v python -u simple_test.py \
    --model_name "${MODEL_NAME}" \
    --attn_type "${ATTN_TYPE}" \
    --dtype "${DTYPE}" \
    --batch_size "${BATCH_SIZE}" \
    --gen_len "${GEN_LEN}" \
    "${TOKEN_BUDGET_ARGS[@]}" \
    "${RECALL_ARGS[@]}"
elif [ "${TEST_MODE}" = "throughput" ]; then
  echo "[INFO] Running throughput_eval/test.py"
  LOW_CPU_MEM_USAGE="${LOW_CPU_MEM_USAGE}" \
  RETRIEVALATTN_FA_FUSED_PREFILL="${RETRIEVALATTN_FA_FUSED_PREFILL}" \
  RETRIEVALATTN_FA_GRAPH_FUSED="${RETRIEVALATTN_FA_GRAPH_FUSED}" \
  RETRIEVALATTN_FA_GRAPH_FUSED_REQUIRE="${RETRIEVALATTN_FA_GRAPH_FUSED_REQUIRE}" \
  RETRIEVALATTN_FA_GRAPH_FUSED_CHECK="${RETRIEVALATTN_FA_GRAPH_FUSED_CHECK}" \
  RETRIEVALATTN_FA_GRAPH_FUSED_QUALITY_FLOOR="${RETRIEVALATTN_FA_GRAPH_FUSED_QUALITY_FLOOR}" \
  RETRIEVALATTN_FA_GRAPH_PROFILE="${RETRIEVALATTN_FA_GRAPH_PROFILE}" \
  RETRIEVALATTN_FA_GRAPH_DEBUG="${RETRIEVALATTN_FA_GRAPH_DEBUG}" \
  RETRIEVALATTN_FA_KERNEL_PROFILE="${RETRIEVALATTN_FA_KERNEL_PROFILE}" \
  RETRIEVALATTN_FA_KERNEL_DEBUG="${RETRIEVALATTN_FA_KERNEL_DEBUG}" \
  RETRIEVALATTN_FA_TOPK_BATCHED="${RETRIEVALATTN_FA_TOPK_BATCHED}" \
  RETRIEVALATTN_FA_KERNEL_MODE="${RETRIEVALATTN_FA_KERNEL_MODE}" \
  RETRIEVALATTN_FA_SPLITK="${RETRIEVALATTN_FA_SPLITK}" \
  RETRIEVALATTN_FA_MERGE_KERNEL="${RETRIEVALATTN_FA_MERGE_KERNEL}" \
  RETRIEVALATTN_FA_FORCE_PYTHON_TOPK="${RETRIEVALATTN_FA_FORCE_PYTHON_TOPK}" \
  RETRIEVALATTN_FUSED_PREFILL_OVERLAP="${RETRIEVALATTN_FUSED_PREFILL_OVERLAP}" \
  RETRIEVALATTN_FUSED_PREFILL_OVERLAP_WORKERS="${RETRIEVALATTN_FUSED_PREFILL_OVERLAP_WORKERS}" \
  RETRIEVALATTN_DECODE_INDEX="${RETRIEVALATTN_DECODE_INDEX}" \
  RETRIEVALATTN_SEED_MODE="${RETRIEVALATTN_SEED_MODE}" \
  RETRIEVALATTN_QUERY_MODE="${RETRIEVALATTN_QUERY_MODE}" \
  RETRIEVALATTN_SCORE_MODE="${RETRIEVALATTN_SCORE_MODE}" \
  RETRIEVALATTN_ROAR_NQ="${RETRIEVALATTN_ROAR_NQ}" \
  RETRIEVALATTN_ROAR_L="${RETRIEVALATTN_ROAR_L}" \
  RETRIEVALATTN_ROAR_M="${RETRIEVALATTN_ROAR_M}" \
  RETRIEVALATTN_ROAR_ENABLE_ENHANCE="${RETRIEVALATTN_ROAR_ENABLE_ENHANCE}" \
  RETRIEVALATTN_ROAR_ENHANCE_L="${RETRIEVALATTN_ROAR_ENHANCE_L}" \
  RETRIEVALATTN_ROAR_ENTRY="${RETRIEVALATTN_ROAR_ENTRY}" \
  RETRIEVALATTN_ROAR_MAX_QUERY_PER_PIVOT="${RETRIEVALATTN_ROAR_MAX_QUERY_PER_PIVOT}" \
  RETRIEVALATTN_ROAR_LOG="${RETRIEVALATTN_ROAR_LOG}" \
  RETRIEVALATTN_ROAR_CPP_THREADS="${RETRIEVALATTN_ROAR_CPP_THREADS}" \
  RETRIEVALATTN_GRAPH_EXPAND="${RETRIEVALATTN_GRAPH_EXPAND}" \
  RETRIEVALATTN_EXPAND_WIDTH="${RETRIEVALATTN_EXPAND_WIDTH}" \
  RETRIEVALATTN_MIN_VISITS="${RETRIEVALATTN_MIN_VISITS}" \
  RETRIEVALATTN_MAX_VISITS="${RETRIEVALATTN_MAX_VISITS}" \
  RETRIEVALATTN_STOP_PATIENCE="${RETRIEVALATTN_STOP_PATIENCE}" \
  RETRIEVALATTN_STOP_MARGIN="${RETRIEVALATTN_STOP_MARGIN}" \
  RETRIEVALATTN_FRONTIER_TOPN="${RETRIEVALATTN_FRONTIER_TOPN}" \
  RETRIEVALATTN_RERANK="${RETRIEVALATTN_RERANK}" \
  RETRIEVALATTN_RERANK_AGG="${RETRIEVALATTN_RERANK_AGG}" \
  RETRIEVALATTN_SEED_RATIO="${RETRIEVALATTN_SEED_RATIO}" \
  RETRIEVALATTN_CAND_MULT="${RETRIEVALATTN_CAND_MULT}" \
  RETRIEVALATTN_SEED_K_MULT="${RETRIEVALATTN_SEED_K_MULT}" \
  RETRIEVALATTN_SEED_PREV_K="${RETRIEVALATTN_SEED_PREV_K}" \
  RETRIEVALATTN_SEED_HUB_K="${RETRIEVALATTN_SEED_HUB_K}" \
  RETRIEVALATTN_SEED_TAIL_K="${RETRIEVALATTN_SEED_TAIL_K}" \
  RETRIEVALATTN_DEBUG="${RETRIEVALATTN_DEBUG}" \
  RETRIEVALATTN_ASSERT_NONEMPTY="${RETRIEVALATTN_ASSERT_NONEMPTY}" \
  RETRIEVALATTN_VALIDATE_PARITY="${RETRIEVALATTN_VALIDATE_PARITY}" \
  RETRIEVALATTN_PARITY_LAYERS="${RETRIEVALATTN_PARITY_LAYERS}" \
  RETRIEVALATTN_PARITY_HEADS="${RETRIEVALATTN_PARITY_HEADS}" \
  RETRIEVALATTN_PARITY_SAMPLE="${RETRIEVALATTN_PARITY_SAMPLE}" \
  RETRIEVALATTN_GRAPH_TRAIN_FRAC="${RETRIEVALATTN_GRAPH_TRAIN_FRAC}" \
  RETRIEVALATTN_GRAPH_SPLIT="${RETRIEVALATTN_GRAPH_SPLIT}" \
  RETRIEVALATTN_GRAPH_SPLIT_SEED="${RETRIEVALATTN_GRAPH_SPLIT_SEED}" \
  RETRIEVALATTN_PARITY_HOLDOUT_ONLY="${RETRIEVALATTN_PARITY_HOLDOUT_ONLY}" \
  RETRIEVALATTN_TRAVERSAL_EVAL="${RETRIEVALATTN_TRAVERSAL_EVAL}" \
  RETRIEVALATTN_TRAVERSAL_EVAL_SAMPLE="${RETRIEVALATTN_TRAVERSAL_EVAL_SAMPLE}" \
  RETRIEVALATTN_DECODE_PROFILE="${RETRIEVALATTN_DECODE_PROFILE}" \
  /usr/bin/time -v python -u throughput_eval/test.py \
    --model_name "${MODEL_NAME}" \
    --attn_type "${ATTN_TYPE}" \
    --dtype "${DTYPE}" \
    --batch_size "${BATCH_SIZE}" \
    --task_name vt \
    "${TOKEN_BUDGET_ARGS[@]}"
else
  echo "[ERROR] Unknown TEST_MODE: ${TEST_MODE}"
  exit 1
fi

if command -v nvidia-smi >/dev/null 2>&1; then
  echo "[INFO] nvidia-smi (after)"
  nvidia-smi
fi

echo "[INFO] Job finished at: $(date)"
