#!/usr/bin/env bash
#SBATCH --job-name=frontier-ruler
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=128000m
#SBATCH --time=01:00:00
#SBATCH --account=zhengya0
#SBATCH --partition=gpu_mig40,spgpu,gpu-rtx6000
#SBATCH --gpus-per-node=1
set -euo pipefail

# Benchmark-ready frontier preset for one RULER task.
# Submit with: sbatch scripts/run_frontier_ruler_batched_one.sh

cd /gpfs/accounts/zhengya_root/zhengya98/minsikky/long_context/RetrievalAttention/worktrees/op-fix

# The prebuilt selector_paged_pq CUDA extension is ABI-matched to the
# cu128 venv (torch 2.11.0+cu128); .venv (torch 2.5.1+cu124) fails its
# import with an undefined c10 symbol. Default to cu128 like the other
# frontier wrappers so bare submissions cannot pick the wrong env.
export HF_VENV_DIR="${HF_VENV_DIR:-.venv_cu128}"
export HF_EXTRA_PYTHONPATH="${HF_EXTRA_PYTHONPATH:-.hf_pydeps_cu128}"

export MODE="${MODE:-pagedpq_batched}"
export OUTPUT_ROOT="${OUTPUT_ROOT:-ruler_eval_result/frontier_batched}"
export TASK_NAME="${TASK_NAME:-niah_single_1}"
export CONTEXT_LEN="${CONTEXT_LEN:-8192}"
export NUM_SAMPLES="${NUM_SAMPLES:-4}"

export SELECTOR_MODE="${SELECTOR_MODE:-fullscan}"
export SELECTOR_BACKEND="${SELECTOR_BACKEND:-cuda_ext}"
export BUDGET="${BUDGET:-4096}"
export ONLINE_CONFIDENCE_RULE="${ONLINE_CONFIDENCE_RULE:-joint_kv_stability}"
export TAIL_MODE="${TAIL_MODE:-vpq_value}"
export TAIL_SCORE_CALIBRATION="${TAIL_SCORE_CALIBRATION:-none}"
export TAIL_PROBE_REL_L2_MAX="${TAIL_PROBE_REL_L2_MAX:-0.020}"
export TAIL_PROXY_MASS_MIN="${TAIL_PROXY_MASS_MIN:-0.990}"
export TAIL_PROXY_MASS_MAX="${TAIL_PROXY_MASS_MAX:-1.0}"
export TAIL_PQ_CORR_MIN="${TAIL_PQ_CORR_MIN:-0.70}"
export TAIL_PQ_RELRMSE_MAX="${TAIL_PQ_RELRMSE_MAX:-inf}"
export RANKED_CONFIDENCE_COST_MODE="${RANKED_CONFIDENCE_COST_MODE:-exact}"
export FRONTIER_EXACT_LOGIT_BACKEND="${FRONTIER_EXACT_LOGIT_BACKEND:-auto}"
export FRONTIER_DENSE_SIM_MAX_CONTEXT_RATIO="${FRONTIER_DENSE_SIM_MAX_CONTEXT_RATIO:-2.0}"
# Default FLIPS to 0 per the adopted standard config (keyT cache off on all
# cards). Caller wins. A/B (jobs 53219181/53224181): predictions/scores
# identical vs. cache-on, only MB counters move <=0.1%; A/A fully deterministic.
export FRONTIER_DENSE_KEY_T_CACHE="${FRONTIER_DENSE_KEY_T_CACHE:-0}"
export FRONTIER_DENSE_KEY_T_CACHE_MAX_GB="${FRONTIER_DENSE_KEY_T_CACHE_MAX_GB:-12.0}"
export FRONTIER_CANONICAL_GPU="${FRONTIER_CANONICAL_GPU:-1}"
export SELECTOR_PQ_PRECOMPUTE_RANK_WEIGHTS="${SELECTOR_PQ_PRECOMPUTE_RANK_WEIGHTS:-1}"
export SELECTOR_PQ_GEOMETRIC_THREADS="${SELECTOR_PQ_GEOMETRIC_THREADS:-512}"
export SELECTOR_PQ_SELECTED_CODEWEIGHT_DELTAS="${SELECTOR_PQ_SELECTED_CODEWEIGHT_DELTAS:-1}"
export SELECTOR_PQ_SELECTED_EXACT_LISTS="${SELECTOR_PQ_SELECTED_EXACT_LISTS:-1}"
export SELECTOR_PQ_THRESHOLD_NATIVE_TOPK="${SELECTOR_PQ_THRESHOLD_NATIVE_TOPK:-1}"
export SELECTOR_PQ_THRESHOLD_TOPK="${SELECTOR_PQ_THRESHOLD_TOPK:-16384}"
export ENABLE_FUSED_GEOMETRIC_OUTPUT="${ENABLE_FUSED_GEOMETRIC_OUTPUT:-1}"
export SELECTOR_PQ_FUSED_DIM_SCAN_OUTPUT="${SELECTOR_PQ_FUSED_DIM_SCAN_OUTPUT:-1}"
source scripts/frontier_canonical_env.sh
if [[ "${FRONTIER_ALLOW_DIAGNOSTIC_MERGE_RISK:-0}" == "1" ]]; then
  export FRONTIER_CANONICAL_GPU=0
  export SELECTOR_PQ_JOINT_MERGE_RISK_POLICY=1
fi

export GEOMETRIC_MIN_BUDGET="${GEOMETRIC_MIN_BUDGET:-${BUDGET}}"
export GEOMETRIC_MAX_BUDGET="${GEOMETRIC_MAX_BUDGET:-65536}"
export GEOMETRIC_GROWTH="${GEOMETRIC_GROWTH:-1.5}"
export GEOMETRIC_PROBE_SCALE="${GEOMETRIC_PROBE_SCALE:-1.5}"
export GEOMETRIC_BUDGET_GRANULARITY="${GEOMETRIC_BUDGET_GRANULARITY:-1024}"
export JOINT_KV_POLICY="${JOINT_KV_POLICY:-k_first_alternating}"
export JOINT_KV_K_BUDGET_FRACS="${JOINT_KV_K_BUDGET_FRACS:-0.10,0.30,0.50,0.70,0.90,1.0}"
export JOINT_KV_V_BUDGET_FRACS="${JOINT_KV_V_BUDGET_FRACS:-0.05,0.10,0.20,0.40,0.60,0.80,1.0}"
export JOINT_KV_THRESHOLD_MODE="${JOINT_KV_THRESHOLD_MODE:-budget_delta_frac}"
export JOINT_KV_THRESHOLD_REFERENCE_FRAC="${JOINT_KV_THRESHOLD_REFERENCE_FRAC:-0.2}"
export JOINT_KV_THRESHOLD_SCALE_SHAPE="${JOINT_KV_THRESHOLD_SCALE_SHAPE:-sqrt}"
export JOINT_KV_THRESHOLD_MIN_SCALE="${JOINT_KV_THRESHOLD_MIN_SCALE:-0.0}"
export JOINT_KV_THRESHOLD_MAX_SCALE="${JOINT_KV_THRESHOLD_MAX_SCALE:-1.5}"
export JOINT_KV_START_STRATEGY="${JOINT_KV_START_STRATEGY:-proxy_mass_m0p9}"
case "${JOINT_KV_SCHEDULE_PRESET:-default}" in
  default)
    DEFAULT_JOINT_KV_K_BUDGETS="4096,8192,14336,32768"
    DEFAULT_JOINT_KV_V_BUDGETS="1024,2048,4096,6144,8192,12288,16384"
    ;;
  coarse)
    DEFAULT_JOINT_KV_K_BUDGETS="4096,8192,32768"
    DEFAULT_JOINT_KV_V_BUDGETS="2048,8192,16384"
    ;;
  coarse2)
    DEFAULT_JOINT_KV_K_BUDGETS="4096,32768"
    DEFAULT_JOINT_KV_V_BUDGETS="4096,16384"
    ;;
  coarse_v8k)
    DEFAULT_JOINT_KV_K_BUDGETS="4096,32768"
    DEFAULT_JOINT_KV_V_BUDGETS="4096,8192"
    ;;
  mid_v8k)
    DEFAULT_JOINT_KV_K_BUDGETS="4096,8192,16384"
    DEFAULT_JOINT_KV_V_BUDGETS="4096,8192"
    ;;
  *)
    echo "unknown JOINT_KV_SCHEDULE_PRESET=${JOINT_KV_SCHEDULE_PRESET}; expected default, coarse, coarse2, coarse_v8k, or mid_v8k" >&2
    exit 2
    ;;
esac
export JOINT_KV_K_BUDGETS="${JOINT_KV_K_BUDGETS:-${DEFAULT_JOINT_KV_K_BUDGETS}}"
export JOINT_KV_V_BUDGETS="${JOINT_KV_V_BUDGETS:-${DEFAULT_JOINT_KV_V_BUDGETS}}"
export JOINT_KV_STABILITY_THRESHOLD="${JOINT_KV_STABILITY_THRESHOLD:-0.002}"

export SELECTED_VALUE_MODE="${SELECTED_VALUE_MODE:-vpq_value}"
export SELECTED_VALUE_EXACT_RULE="${SELECTED_VALUE_EXACT_RULE:-global_residual_risk}"
export SELECTED_VALUE_EXACT_TOP="${SELECTED_VALUE_EXACT_TOP:-0}"
export SELECTED_VALUE_EXACT_MASS="${SELECTED_VALUE_EXACT_MASS:-0.0}"
export SELECTED_VALUE_MIN_EXACT_TOP="${SELECTED_VALUE_MIN_EXACT_TOP:-0}"
export SELECTED_VALUE_MAX_EXACT_TOP="${SELECTED_VALUE_MAX_EXACT_TOP:-0}"
export VALUE_CODE_STAT_BYTES="${VALUE_CODE_STAT_BYTES:-2}"

export TAIL_BLEND="${TAIL_BLEND:-1.0}"
export NATIVE_DECODE_TAIL="${NATIVE_DECODE_TAIL:-1}"
export PROFILE_NATIVE_OPS="${PROFILE_NATIVE_OPS:-0}"

export PAGE_SIZE="${PAGE_SIZE:-5632}"
export PREFILL_CHUNK_SIZE="${PREFILL_CHUNK_SIZE:-0}"
export PREFILL_SELECTOR_BACKEND="${PREFILL_SELECTOR_BACKEND:-native}"
if [[ -z "${PREFILL_SELECTOR_TILE_SIZE+x}" ]]; then
  if [[ "${PREFILL_SELECTOR_BACKEND}" == "native" ]]; then
    export PREFILL_SELECTOR_TILE_SIZE=2048
  else
    export PREFILL_SELECTOR_TILE_SIZE=256
  fi
else
  export PREFILL_SELECTOR_TILE_SIZE
fi
export PREFILL_SELECTOR_PAGE_BLOCK_SIZE="${PREFILL_SELECTOR_PAGE_BLOCK_SIZE:-0}"
export PREFILL_TAIL_SCORE_REUSE="${PREFILL_TAIL_SCORE_REUSE:-1}"
export PREFILL_ATTENTION_BACKEND="${PREFILL_ATTENTION_BACKEND:-native}"
export INDEX_BUILD_BACKEND="${INDEX_BUILD_BACKEND:-torch_gpu}"
export NPROBES="${NPROBES:-16,32,64,128,256,512}"

export SUBVECS="${SUBVECS:-4}"
export SUBBITS="${SUBBITS:-8}"
export VALUE_SUBVECS="${VALUE_SUBVECS:-1}"
export VALUE_SUBBITS="${VALUE_SUBBITS:-4}"
export VALUE_PQ_GROUP_PAGES="${VALUE_PQ_GROUP_PAGES:-1}"
export KMEANS_ITERS="${KMEANS_ITERS:-3}"

exec bash scripts/run_ruler_pagedpq_stream_smoke_one.sh
