#!/usr/bin/env bash
set -euo pipefail

cd /scratch/zhengya_root/zhengya98/minsikky/long_context/RetrievalAttention

export OUTPUT_ROOT="${OUTPUT_ROOT:-attention_efficiency_result/selected_key_compression_20260514_smoke}"
export RUN_NAME="${RUN_NAME:?RUN_NAME is required}"
export ONLINE_CONFIDENCE_RULE="${ONLINE_CONFIDENCE_RULE:-geometric_probe_tail_switch}"
export DECODE_LENGTHS="${DECODE_LENGTHS:-128000}"
export MAX_QIDX_PER_DECODE="${MAX_QIDX_PER_DECODE:-1}"
export DEVICE="${DEVICE:-cpu}"

export SELECTOR_MODE="${SELECTOR_MODE:-fullscan}"
export TAIL_PROBE_REL_L2_MAX="${TAIL_PROBE_REL_L2_MAX:-0.020}"
export PROXY_MASS_TARGET="${PROXY_MASS_TARGET:-0.99}"
export TAIL_PROXY_MASS_MIN="${TAIL_PROXY_MASS_MIN:-0.99}"
export TAIL_PQ_CORR_MIN="${TAIL_PQ_CORR_MIN:-0.70}"
export GEOMETRIC_MIN_BUDGET="${GEOMETRIC_MIN_BUDGET:-4096}"
export GEOMETRIC_MAX_BUDGET="${GEOMETRIC_MAX_BUDGET:-90000}"
export GEOMETRIC_MAX_BUDGET_BY_HEAD="${GEOMETRIC_MAX_BUDGET_BY_HEAD:-0:120000,1:120000}"
export LONG_CONTEXT_THRESHOLD="${LONG_CONTEXT_THRESHOLD:-0}"
export LONG_GEOMETRIC_MAX_BUDGET="${LONG_GEOMETRIC_MAX_BUDGET:-0}"
export LONG_GEOMETRIC_MAX_BUDGET_BY_HEAD="${LONG_GEOMETRIC_MAX_BUDGET_BY_HEAD:-}"
export GEOMETRIC_GROWTH="${GEOMETRIC_GROWTH:-1.5}"
export GEOMETRIC_PROBE_SCALE="${GEOMETRIC_PROBE_SCALE:-1.5}"
export GEOMETRIC_BUDGET_GRANULARITY="${GEOMETRIC_BUDGET_GRANULARITY:-1024}"

export TAIL_MODE="${TAIL_MODE:-vpq_value}"
export SELECTED_VALUE_MODE="${SELECTED_VALUE_MODE:-vpq_value}"
export SELECTED_VALUE_EXACT_RULE="${SELECTED_VALUE_EXACT_RULE:-selected_mass}"
export SELECTED_VALUE_EXACT_MASS="${SELECTED_VALUE_EXACT_MASS:-0.98}"
export SELECTED_VALUE_MIN_EXACT_TOP="${SELECTED_VALUE_MIN_EXACT_TOP:-1024}"
export SELECTED_VALUE_MAX_EXACT_TOP="${SELECTED_VALUE_MAX_EXACT_TOP:-11264}"
export SELECTED_VALUE_MAX_EXACT_TOP_BY_HEAD="${SELECTED_VALUE_MAX_EXACT_TOP_BY_HEAD:-0:0,1:0}"
export SELECTED_VALUE_EXACT_ALL_FRACTION_MIN="${SELECTED_VALUE_EXACT_ALL_FRACTION_MIN:-0.95}"
export LONG_SELECTED_VALUE_EXACT_MASS="${LONG_SELECTED_VALUE_EXACT_MASS:--1.0}"
export LONG_SELECTED_VALUE_MAX_EXACT_TOP="${LONG_SELECTED_VALUE_MAX_EXACT_TOP:--1}"
export LONG_SELECTED_VALUE_MAX_EXACT_TOP_BY_HEAD="${LONG_SELECTED_VALUE_MAX_EXACT_TOP_BY_HEAD:-}"

export SUBVECS="${SUBVECS:-4}"
export SUBBITS="${SUBBITS:-8}"
export VALUE_SUBVECS="${VALUE_SUBVECS:-1}"
export VALUE_SUBBITS="${VALUE_SUBBITS:-4}"
export NPROBES="${NPROBES:-512}"

export SELECTED_KEY_MODE="${SELECTED_KEY_MODE:-exact}"
export SELECTED_KEY_CALIBRATION_PROBES="${SELECTED_KEY_CALIBRATION_PROBES:-0}"
export SELECTED_KEY_CALIBRATION_BANDS="${SELECTED_KEY_CALIBRATION_BANDS:-8}"
export SELECTED_KEY_EXACT_SELECTOR_MASS="${SELECTED_KEY_EXACT_SELECTOR_MASS:-0.0}"
export SELECTED_KEY_MIN_EXACT_TOP="${SELECTED_KEY_MIN_EXACT_TOP:-0}"
export SELECTED_KEY_MAX_EXACT_TOP="${SELECTED_KEY_MAX_EXACT_TOP:-0}"
export SELECTED_KEY_MIN_CONTEXT="${SELECTED_KEY_MIN_CONTEXT:-0}"

bash scripts/run_confidence_budget_rule_one.sh
